version: '3'

services:
    livekit:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nest-backend-template
        environment:
            - CLIENT_ORIGIN=http://localhost
            - CLIENT_PORT=4005
            - DATABASE_URL=postgres://postgres:postgres@postgres:5432/doctor_care
            - LIVEKIT_API_KEY=APIkoRTNtywxXmm
            - LIVEKIT_API_SECRET=1deGtNvQ149cFZyikh5DoKxZtvWwXQijyt71QISB8hJ
            - LIVEKIT_URL=wss://lifeforce-care-dn4w5jlr.livekit.cloud
            - ORY_PROJECT_SLUG=loving-curie-fi4rhv339e
            - ORY_PROJECT_ID=34a182e7-5e06-4078-9c35-5dde3b0bacb1
            - ORY_API_KEY=ory_pat_oXMyiEFdTN4YQfSBCClnUA3JVS7DN508
            - NODE_ENV=development
        networks:
            - dockernetwork
        depends_on:
            - postgres
        ##restart: always
        ports:
            - '3000:3000'
        # restart: always
    postgres:
        image: postgres:latest
        container_name: postgres
        # volumes:
        #   - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            # DB_HOST: 'localhost'
            POSTGRES_PORT: 5432
            POSTGRES_DB: doctor_care
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'

        networks:
            - dockernetwork
        restart: always

networks:
    dockernetwork:
        driver: bridge
